name: "MM Laravel PHPUnit"
description: "A GitHub action to run your Laravel project's PHPUnit test suite."
branding:
  icon: "check-circle"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
